version: '3.8'
services:
  app:
    build: .
    # image: php:8.1-fpm  # убираем или комментируем
    container_name: php_app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: carsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
